### ISSUE TITLE
FCM is not recognised during import

### ISSUE THREAD

**Issue by Bazmundi** [mpuheim/PyOpenFCM#1]
- Windows 10
- Python 3.6.3
- running in venv
- Followed instructions at https://github.com/mpuheim/PyOpenFCM
- Added "pip install numpy" since you appear to have left that off the dependencies in the install instructions
- ran the web service to checkout the install, web service was running
- started python and used "from fcmapi import FCM" per example but exception was raised as fcmlib was not recognised.

Actually looks like the setup ignored the fact it was being run from venv and drove the install into the root python location.

**Comment by mpuheim** [comment]
use "from fcmlib import FCM"
